Repository eshoku/frontend, pull requests merged in 2021-11, with the labels that each got.

#63 Implement dynamic routing for room page
  pages/api/room.ts
  pages/api/room/[id].ts
  pages/api/user.ts
  pages/room.tsx
  pages/room/[id].tsx
  pages/settings.tsx
  pages/userinfo.tsx
  states/currentUser.tsx
  types/RoomInfo.ts
  types/UserInfo.ts
  utils/commonAxios.ts
  utils/roomApiController.ts
Labels: Priority: high, BFF

#69 Setup production API
  utils/commonAxios.ts
Labels: BFF, V1

#72 Update settings page
  next.config.js
  pages/settings.tsx
Labels: V1

#73 Implement join and leave room feature
  components/roomActionBtn.module.scss
  components/roomActionBtn.tsx
  pages/api/room/join/[id].ts
  pages/api/room/leave/[id].ts
  pages/room/[id].tsx
  types/RoomInfo.ts
  utils/roomActionController.ts
  utils/roomApiController.ts
Labels: BFF, V1

#76 Fixes #71
  components/nav.module.scss
Labels: bug
