Repository eshoku/frontend, pull requests merged in 2021-12, with the labels that each got.

#100 Implement joining page
  components/roomActionBtn.tsx
  pages/room/[id].tsx
  pages/room/join/[id].tsx
  styles/room.module.scss
Labels: V1

#107 Implement sharing feature to room page
  .eslintrc.json
  components/buttonCard.tsx
  components/roomActionBtn.module.scss
  components/roomActionBtn.tsx
  pages/index.tsx
  pages/room/[id].tsx
  pages/room/join/[id].tsx
  pages/signup.tsx
  styles/globals.scss
  styles/room.module.scss
Labels: enhancement, design

#99 Configure PWA
  next.config.js
  package.json
  pages/_document.tsx
  pages/signup.tsx
  pages/userinfo.tsx
  public/.gitkeep
  public/apple-touch-icon.png
  public/icons/android-chrome-128x128.png
  public/icons/android-chrome-192x192.png
  public/icons/android-chrome-384x384.png
  public/icons/android-chrome-48x48.png
  public/icons/android-chrome-512x512.png
  public/icons/android-chrome-72x72.png
  public/icons/android-chrome-96x96.png
  public/icons/maskable_icon_x128.png
  public/icons/maskable_icon_x192.png
  public/icons/maskable_icon_x384.png
  public/icons/maskable_icon_x48.png
  public/icons/maskable_icon_x512.png
  public/icons/maskable_icon_x72.png
  public/icons/maskable_icon_x96.png
  public/manifest.json
  public/splashscreens/ipad_splash.png
  public/splashscreens/ipadpro1_splash.png
  public/splashscreens/ipadpro2_splash.png
  public/splashscreens/ipadpro3_splash.png
  public/splashscreens/iphone5_splash.png
  public/splashscreens/iphone6_splash.png
  public/splashscreens/iphoneplus_splash.png
  public/splashscreens/iphonex_splash.png
  public/splashscreens/iphonexr_splash.png
  public/splashscreens/iphonexsmax_splash.png
  yarn.lock
Labels: enhancement, V1 feature, V2 feature
